### ISSUE TITLE
14. Add User info Card in Case detail Page

### ISSUE THREAD

**Issue by dragonite20** [uoftblueprint/homes-for-heroes#19]
Add a MUI card , that adds the names, email and essential information for the user .
![image](https://user-images.githubusercontent.com/42284448/141231711-bd2b5663-92ef-45f4-8fcf-345e7109ab56.png)

**Comment by sunnykgh** [comment]
Do you want the layout of the component to be similar to the one in the image? I'm having a hard time making the layout work for mobile.

**Comment by dragonite20** [comment]
Yes only the top part with the User info
