### ISSUE TITLE
3. Handling Login/ Authetication in the Backend

### ISSUE THREAD

**Issue by dragonite20** [uoftblueprint/homes-for-heroes#3]
Handle Login for User/Signup 
 -> The user will log in using  email and Username and password 
 -> Signup will be handled by sending sign up links for admin users 
->  Setup session tokens

**Comment by ArcaneWizard** [comment]
Hey, I'm got some experience with JWT tokens. Would be interested in implementing this. Although, I don't see the node backend and a database set up yet. Is it in the works? If needed, I could also temporarily use a PostgreSQL or MongoDB database with basic user info (name, password, email, etc.) for now.
