### ISSUE TITLE
4.Schema for Admin User and Client User

### ISSUE THREAD

**Issue by dragonite20** [uoftblueprint/homes-for-heroes#4]
Admin User Table:
Name
Email
Phone Number
Password
Address
Admin User Id(Auto generate Primary key)

User Table:
Name
Email
Phone Number
Password
Client Use Id(Auto generate Primary key)

Case Management:
Client Use Id
Admin User Id
Notes
last_update

**Comment by yrao6597** [comment]
Table 1 and 2 (admin and client users tables) created on local server and need review for datatypes and constraints; 
Table 3 (cases table): last_update column needs to be further confirmed regarding datatype

**Comment by dragonite20** [comment]
Opening this issue for Yvonne!
